services:
  docs:
    container_name: pokewalker-docs
    image: ghcr.io/${GITHUB_OWNER}/pokewalker-wiki:latest
    restart: unless-stopped
    ports:
      - "${WIKI_PORT}:80"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    command: pokewalker-docs --interval 30 --cleanup
    environment:
      - WATCHTOWER_CLEANUP=true
